import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=await PGlite.create();
await db.exec(`create schema auth; create role anon; create role authenticated; create role service_role bypassrls;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort()) await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
const a='00000000-0000-0000-0000-000000000001', b='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}'),('${b}');
insert into radar.teams(id,name) values('${a}','Team A'),('${b}','Team B');
insert into radar.team_members values('${a}','${a}','OWNER',now()),('${b}','${b}','OWNER',now());
insert into radar.team_profiles(team_id,profile) values('${a}','{"region":"Seoul"}'),('${b}','{"region":"Busan"}');
insert into radar.telegram_subscriptions(team_id,chat_id) values('${a}','private-id');`);
await db.exec(`set role authenticated; set request.jwt.claim.sub='${a}';`);
assert.equal((await db.query('select * from radar.team_profiles')).rows.length,1);
assert.equal((await db.query('select * from radar.team_profiles')).rows[0].team_id,a);
assert.equal((await db.query('select * from radar.telegram_subscriptions')).rows.length,0);
assert.equal((await db.query(`update radar.team_profiles set profile='{}' where team_id='${b}' returning team_id`)).rows.length,0);
await assert.rejects(db.query(`insert into radar.team_profile_versions(team_id,version,profile) values('${b}',1,'{}')`));
await assert.rejects(db.query(`insert into radar.admin_users values('${a}')`));
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select * from radar.team_profiles'));
await db.exec('reset role;');
const rls=await db.query("select relname from pg_class c join pg_namespace n on c.relnamespace=n.oid where n.nspname='radar' and c.relkind='r' and not c.relrowsecurity");
assert.deepEqual(rls.rows,[]);
console.log('PASS: migration applied; team isolation, cross-team writes, Telegram privacy, admin escalation, anonymous access, all-table RLS');
await db.close();
