"""Generate a SQL mirror of the GFC relevance rules from radar/relevance.py.

Used to classify opportunities that are already stored, without re-running the
collection pipeline against production. The rule tables in radar/relevance.py
remain the single source of truth: this file only transcribes them, so the SQL
must always be regenerated rather than edited by hand.

    python -m tools.export_relevance_sql > /tmp/relevance.sql

The generated function is an operator backfill aid, not part of the weekly
publication path, which always uses the Python classifier.
"""
import sys

from radar import relevance


def sql_regex(pattern):
    # POSIX ARE spells the word boundary \y; everything else used by the rule
    # tables (\s, (?:...), {n,m}, [^\n], alternation) is shared with Python.
    return pattern.replace('\\b', '\\y').replace("'", "''")


def quote(label):
    return "'" + label.replace("'", "''") + "'"


def branches(rules, target):
    """First match wins, mirroring the Python `found[0]['label']` reason."""
    lines = []
    for label, compiled in rules:
        lines.append(f"  if {target} is null and t ~* '{sql_regex(compiled.pattern)}' then\n"
                     f"    {target}:={quote(label)}; end if;")
    return '\n'.join(lines)


def collected(rules, target):
    """Every match, de-duplicated and joined, mirroring the Python ' · ' join."""
    lines = []
    for label, compiled in rules:
        # The ::text casts matter: `text[] || 'literal'` parses the literal as an
        # array literal and fails at runtime on any value containing '·'.
        lines.append(f"  if t ~* '{sql_regex(compiled.pattern)}' and not {target} @> array[{quote(label)}::text] then\n"
                     f"    {target}:={target}||{quote(label)}::text; end if;")
    return '\n'.join(lines)


def generate():
    return f"""-- GENERATED by tools/export_relevance_sql.py from radar/relevance.py.
-- Do not edit by hand; regenerate when the rule tables change.
create or replace function startup_radar.gfc_relevance_v1_1(
 p_title text,p_applicant text,p_support text)
returns jsonb language plpgsql immutable security invoker set search_path='' as $fn$
declare
 t text; hard text; generic text; event text; deliverable text;
 core text[]:='{{}}'; restriction text[]:='{{}}';
 core_reason text; restriction_summary text; region text;
begin
 t:=concat_ws(E'\\n',coalesce(p_title,''),
   left(coalesce(p_applicant,''),{relevance.APPLICANT_EVIDENCE_CHARS}),
   left(coalesce(p_support,''),{relevance.SUPPORT_EVIDENCE_CHARS}));
{branches(relevance.HARD_EXCLUSION, 'hard')}
{collected(relevance.CORE_STARTUP, 'core')}
 core_reason:=left(array_to_string(core,' · '),200);
 if hard is not null and cardinality(core)>0 then
  return jsonb_build_object('relevance_status','REVIEW_REQUIRED','startup_leverage','UNKNOWN',
   'applicability','UNKNOWN','startup_leverage_reason','상충 신호: 운영자 확인 필요',
   'restriction_summary',null); end if;
 if hard is not null then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',hard,'restriction_summary',null); end if;
{branches(relevance.GENERIC_SOFT_EXCLUSION, 'generic')}
{branches(relevance.EVENT_SOFT_EXCLUSION, 'event')}
{branches(relevance.DELIVERABLE, 'deliverable')}
 if event is not null and deliverable is null then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',event,'restriction_summary',null); end if;
 if generic is not null and cardinality(core)=0 then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',generic,'restriction_summary',null); end if;
 if cardinality(core)=0 then
  if length(btrim(t))<{relevance._MIN_EVIDENCE_TEXT} then
   return jsonb_build_object('relevance_status','REVIEW_REQUIRED','startup_leverage','UNKNOWN',
    'applicability','UNKNOWN','startup_leverage_reason','근거 텍스트 부족: 운영자 확인 필요',
    'restriction_summary',null); end if;
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason','창업 실행 레버리지 근거 없음',
   'restriction_summary',null); end if;
{collected(relevance.RESTRICTION, 'restriction')}
 region:=(select (regexp_match(coalesce(p_title,''),'{sql_regex(relevance._REGION_PREFIX.pattern)}'))[1]);
 if region is not null then
  restriction:=restriction||(region||' 지역 사업')::text;
 else
  region:=(select (regexp_match(t,'{sql_regex(relevance._REGION_TEXT.pattern)}'))[1]);
  if region is not null then
   restriction:=restriction||(region||' 소재 기업')::text;
  elsif t ~* '{sql_regex(relevance._REGION_LOCAL.pattern)}' then
   restriction:=restriction||'주관기관 관내 소재 기업'::text;
  end if;
 end if;
 if cardinality(restriction)=0 then
  return jsonb_build_object('relevance_status','GFC_RELEVANT','startup_leverage','HIGH',
   'applicability','BROAD','startup_leverage_reason',core_reason,'restriction_summary',null); end if;
 restriction_summary:=left(array_to_string(restriction,' · '),200);
 return jsonb_build_object('relevance_status','CONDITIONAL','startup_leverage','HIGH',
  'applicability','RESTRICTED','startup_leverage_reason',core_reason,
  'restriction_summary',restriction_summary);
end $fn$;
revoke all on function startup_radar.gfc_relevance_v1_1(text,text,text) from public,anon,authenticated;
grant execute on function startup_radar.gfc_relevance_v1_1(text,text,text) to service_role;
"""


if __name__ == '__main__':
    sys.stdout.write(generate())
