"""Generate a SQL mirror of the GFC stage-fit rules from radar/stage.py.

Used to classify stage fit for already-stored program versions and published
items without re-running collection, and to calibrate the rules against real
data. radar/stage.py stays the single source of truth; regenerate, never edit.

    python -m tools.export_stage_sql > supabase/migrations/<ts>_gfc_stage_backfill_function.sql

The weekly publication path always uses the Python classifier.
"""
import sys

from radar import stage


def sql_regex(pattern):
    return pattern.replace('\\b', '\\y').replace("'", "''")


def stage_block(code):
    """Total match count across the stage's rules, on the text that stage may read."""
    source = 't_desc' if code == 'STAGE_4' else 't_all'
    counts = ' + '.join(
        f"(select count(*) from regexp_matches({source},'{sql_regex(compiled.pattern)}','gi'))"
        for _, compiled in stage.SIGNALS[code])
    return f"  n:={counts};\n  if n>0 then found:=found||row('{code}',n,{stage.ORDER[code]})::startup_radar.stage_hit; end if;"


def generate():
    blocks = '\n'.join(stage_block(code) for code, _ in stage.STAGES)
    labels = ','.join(f"('{code}','{label}')" for code, label in stage.STAGES)
    return f"""-- GENERATED by tools/export_stage_sql.py from radar/stage.py ({stage.STAGE_VERSION}).
-- Do not edit by hand; regenerate when the rule tables change.
do $$ begin
 if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace
                where n.nspname='startup_radar' and t.typname='stage_hit') then
  create type startup_radar.stage_hit as (code text, hits bigint, ord integer);
 end if;
end $$;

create or replace function startup_radar.stage_label(p_code text) returns text
language sql immutable security invoker set search_path='' as $$
 select label from (values {labels}) as s(code,label) where s.code=p_code
$$;

create or replace function startup_radar.gfc_stage_v1_0(
 p_title text,p_applicant text,p_support text)
returns text[] language plpgsql immutable security invoker set search_path='' as $fn$
declare
 t_all text; t_desc text; n bigint; found startup_radar.stage_hit[]:='{{}}';
begin
 -- STAGE_4 never reads the applicant summary: eligibility is not stage evidence.
 t_desc:=concat_ws(E'\\n',left(coalesce(p_title,''),{stage.TITLE_CHARS}),left(coalesce(p_support,''),{stage.SUPPORT_CHARS}));
 t_all:=concat_ws(E'\\n',left(coalesce(p_title,''),{stage.TITLE_CHARS}),left(coalesce(p_applicant,''),{stage.APPLICANT_CHARS}),left(coalesce(p_support,''),{stage.SUPPORT_CHARS}));
{blocks}
 if cardinality(found)=0 then return '{{}}'::text[]; end if;
 return coalesce((select array_agg(code order by ord) from (
   select h.code,h.ord from unnest(found) as h order by h.hits desc, h.ord asc limit {stage.MAX_STAGES}) top),'{{}}'::text[]);
end $fn$;
revoke all on function startup_radar.gfc_stage_v1_0(text,text,text) from public,anon,authenticated;
grant execute on function startup_radar.gfc_stage_v1_0(text,text,text) to service_role;
grant execute on function startup_radar.stage_label(text) to authenticated,service_role;
"""


if __name__ == '__main__':
    sys.stdout.write(generate())
