-- GENERATED by tools/export_relevance_sql.py from radar/relevance.py.
-- Do not edit by hand; regenerate when the rule tables change.
create or replace function startup_radar.gfc_relevance_v1_1(
 p_title text,p_applicant text,p_support text)
returns jsonb language plpgsql immutable security invoker set search_path='' as $fn$
declare
 t text; hard text; generic text; event text; deliverable text;
 core text[]:='{}'; restriction text[]:='{}';
 core_reason text; restriction_summary text; region text;
begin
 t:=concat_ws(E'\n',coalesce(p_title,''),
   left(coalesce(p_applicant,''),500),
   left(coalesce(p_support,''),400));
  if hard is null and t ~* '착한가격(업소)?' then
    hard:='착한가격업소'; end if;
  if hard is null and t ~* '(카드|결제|가맹점)\s*수수료' then
    hard:='카드·결제 수수료 지원'; end if;
  if hard is null and t ~* '소상공인[^\n]{0,20}(경영\s*(안정|개선|회복)|버팀목|보조금|지원금|융자)' then
    hard:='소상공인 경영비용 지원'; end if;
  if hard is null and t ~* '경영\s*(안정|개선)\s*자금|운전자금|긴급\s*경영' then
    hard:='경영안정·운전자금'; end if;
  if hard is null and t ~* '(임차료|임대료|전기\s*요금|공과금|관리비)\s*(지원|보전|감면)' then
    hard:='임차료·공과금 보전'; end if;
  if hard is null and t ~* '(특례\s*)?신용\s*보증|보증료\s*(지원|감면)' then
    hard:='신용보증·보증료 지원'; end if;
  if hard is null and t ~* '(물류비|운송비|배송비|택배비)\s*(지원|보전)' then
    hard:='물류·운송비 보전'; end if;
  if hard is null and t ~* '고용\s*(장려금|유지)|인건비\s*지원|채용\s*지원금|일자리\s*장려' then
    hard:='고용장려·인건비 지원'; end if;
  if hard is null and t ~* '(신입|경력)?\s*(사원|직원|연구원)\s*채용|인턴(십|사원)?\s*모집|체험형\s*인턴|인턴\s*모집|서포터즈\s*모집|아르바이트' then
    hard:='채용·인턴 모집'; end if;
  if hard is null and t ~* '가족친화\s*인증|근로자\s*복지|복지\s*포인트' then
    hard:='가족친화·근로자 복지 인증'; end if;
  if hard is null and t ~* '직무\s*발명\s*보상' then
    hard:='직무발명보상 인증'; end if;
  if hard is null and t ~* '표창|포상|유공자|시상식|수상\s*기업\s*선정' then
    hard:='표창·포상·시상'; end if;
  if hard is null and t ~* '안전보건|중대재해|산업안전|위생\s*관리|소방\s*(점검|안전)' then
    hard:='안전·위생·규제 준수'; end if;
  if hard is null and t ~* '스마트\s*공장|뿌리\s*(기업|산업|기술)|공정\s*(개선|혁신|연구)|생산\s*설비|제조\s*공정|자동화\s*설비' then
    hard:='제조공정·설비 고도화'; end if;
  if hard is null and t ~* '국산화|제조\s*(디지털\s*전환|디지털전환|\yDX\y)' then
    hard:='부품 국산화·제조 DX'; end if;
  if hard is null and t ~* '(보험료|부담금|수수료)\s*(지원|보전|감면)|책임보험' then
    hard:='보험료·부담금 보전'; end if;
  if hard is null and t ~* '사업\s*(재편|전환)\s*(지원|컨설팅)?|산업\s*위기|구조\s*조정|전환\s*성장' then
    hard:='사업재편·구조조정'; end if;
  if hard is null and t ~* '장터|푸드\s*트럭|팝업\s*스토어|기획\s*판매전|직거래|플리마켓|동행\s*축제' then
    hard:='직판·행사 판매 참여'; end if;
  if hard is null and t ~* '사회적\s*경제|사회연대\s*경제|공공\s*구매|마을\s*기업|협동조합\s*지원' then
    hard:='사회적경제·공공구매'; end if;
  if t ~* '액셀러레이[팅터]|엑셀러레이[팅터]|배치\s*(프로그램|모집|선발)|\ybatch\y|accelerat|인큐베이[팅션]|레지던시|residency' and not core @> array['액셀러레이팅·배치 선발'::text] then
    core:=core||'액셀러레이팅·배치 선발'::text; end if;
  if t ~* '창업\s*보육|보육\s*센터|입주\s*(기업|팀|기업체|공간|모집|신청)|창업\s*공간|메이커\s*스페이스' and not core @> array['창업 보육·입주 공간'::text] then
    core:=core||'창업 보육·입주 공간'::text; end if;
  if t ~* '\yIR\y|데모\s*데이|demo\s*day|investor\s*day|pitch(ing)?\s*day|투자\s*(매칭|연계|유치\s*지원|설명회|상담회)|피칭|피치\s*덱|투자자\s*매칭|쇼케이스' and not core @> array['투자 매칭·IR·데모데이'::text] then
    core:=core||'투자 매칭·IR·데모데이'::text; end if;
  if t ~* '\yMVP\y|프로토타입|시제품|시작품|제품\s*개발\s*지원' and not core @> array['MVP·프로토타입 제작'::text] then
    core:=core||'MVP·프로토타입 제작'::text; end if;
  if t ~* '\yPoC\y|실증|테스트\s*베드|리빙\s*랩' and not core @> array['실증·PoC·테스트베드'::text] then
    core:=core||'실증·PoC·테스트베드'::text; end if;
  if t ~* '오픈\s*이노베이션|open\s*innovation|대\-?중견\s*연계|수요\s*기업\s*매칭' and not core @> array['오픈이노베이션 협업'::text] then
    core:=core||'오픈이노베이션 협업'::text; end if;
  if t ~* '사업화\s*(지원|자금|연계)|제품화|상용화' and not core @> array['사업화·상용화 지원'::text] then
    core:=core||'사업화·상용화 지원'::text; end if;
  if t ~* '창업\s*(경진대회|공모전|대회|챌린지)|스타트업\s*(경진대회|공모전|챌린지)|아이디어\s*공모' and not core @> array['창업 경진대회·공모전'::text] then
    core:=core||'창업 경진대회·공모전'::text; end if;
  if t ~* '예비\s*창업(자|팀|패키지)|초기\s*창업(자|패키지)|창업\s*도약|재도전\s*창업|청년\s*창업\s*사관' and not core @> array['예비·초기 창업자 선발'::text] then
    core:=core||'예비·초기 창업자 선발'::text; end if;
  if t ~* '기술\s*(이전|사업화)|기술\s*실용화' and not core @> array['기술이전·기술사업화'::text] then
    core:=core||'기술이전·기술사업화'::text; end if;
  if t ~* '(글로벌|해외|국제|현지)[^\n]{0,20}(진출|실증|파트너|바이어\s*매칭|투자자|액셀러|법인\s*설립)|(스타트업|창업\s*기업)[^\n]{0,15}(통합관|파빌리온|공동관)' and not core @> array['글로벌 진출 실행'::text] then
    core:=core||'글로벌 진출 실행'::text; end if;
  if t ~* '(창업|스타트업|투자)\s*(법률|계약|지분|주주간|특허|IP)|주주간\s*계약|지분\s*구조|투자\s*계약|스톡옵션' and not core @> array['창업 특화 법률·지분·IP'::text] then
    core:=core||'창업 특화 법률·지분·IP'::text; end if;
 core_reason:=left(array_to_string(core,' · '),200);
 if hard is not null and cardinality(core)>0 then
  return jsonb_build_object('relevance_status','REVIEW_REQUIRED','startup_leverage','UNKNOWN',
   'applicability','UNKNOWN','startup_leverage_reason','상충 신호: 운영자 확인 필요',
   'restriction_summary',null); end if;
 if hard is not null then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',hard,'restriction_summary',null); end if;
  if generic is null and t ~* '판로\s*(개척|지원)|전시회\s*참가|박람회\s*참가|시장\s*개척단|무역\s*사절단|수출\s*바우처|해외\s*규격\s*인증' then
    generic:='일반 판로·전시 참가 지원'; end if;
  if generic is null and t ~* '(규격|시험|성적서|경영|품질)\s*인증|인증\s*획득|일반\s*컨설팅|경영\s*컨설팅' then
    generic:='일반 인증·컨설팅 지원'; end if;
  if generic is null and t ~* '교육생\s*모집|직무\s*교육|장비\s*교육|역량\s*강화\s*교육|아카데미\s*수강' then
    generic:='일반 교육 과정'; end if;
  if event is null and t ~* '특강|강연|세미나|설명회|간담회|컨퍼런스|포럼|네트워킹|밋업|커피챗|토크\s*콘서트' then
    event:='일회성 강연·행사'; end if;
  if event is null and t ~* '성공\s*(사례|스토리)|후기|이야기|경험\s*공유' then
    event:='사례·후기 공유'; end if;
  if deliverable is null and t ~* '\yMVP\y|프로토타입|시제품|시작품' then
    deliverable:='MVP·프로토타입 결과물'; end if;
  if deliverable is null and t ~* '\yPoC\y|실증|테스트\s*베드' then
    deliverable:='실증·PoC 수행'; end if;
  if deliverable is null and t ~* '데모\s*데이|demo\s*day|\yIR\s*(피칭|덱|자료|발표)|투자\s*(매칭|연계)' then
    deliverable:='IR·데모데이 선발'; end if;
  if deliverable is null and t ~* '액셀러레이[팅터]|배치\s*(프로그램|선발)|accelerat' then
    deliverable:='액셀러레이팅 선발'; end if;
  if deliverable is null and t ~* '사업화\s*(지원|자금)|상용화' then
    deliverable:='사업화·상용화 지원'; end if;
  if deliverable is null and t ~* '고객\s*(발굴|검증|인터뷰)|시장\s*검증|\yBM\y\s*검증|비즈니스\s*모델\s*검증' then
    deliverable:='고객·시장 검증 수행'; end if;
 if event is not null and deliverable is null then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',event,'restriction_summary',null); end if;
 if generic is not null and cardinality(core)=0 then
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason',generic,'restriction_summary',null); end if;
 if cardinality(core)=0 then
  if length(btrim(t))<80 then
   return jsonb_build_object('relevance_status','REVIEW_REQUIRED','startup_leverage','UNKNOWN',
    'applicability','UNKNOWN','startup_leverage_reason','근거 텍스트 부족: 운영자 확인 필요',
    'restriction_summary',null); end if;
  return jsonb_build_object('relevance_status','OUT_OF_SCOPE','startup_leverage','LOW',
   'applicability','UNKNOWN','startup_leverage_reason','창업 실행 레버리지 근거 없음',
   'restriction_summary',null); end if;
  if t ~* '바이오|헬스\s*케어|의료\s*기기|제약|반도체|이차\s*전지|배터리|소재\s*부품\s*장비|디스플레이|조선|자동차\s*부품|방위\s*산업|우주\s*항공|농업|수산|축산|식품\s*산업|화학\s*산업|섬유|뿌리\s*산업|관광|콘텐츠\s*산업' and not restriction @> array['특정 산업 분야 한정'::text] then
    restriction:=restriction||'특정 산업 분야 한정'::text; end if;
  if t ~* '사업자\s*등록(증|자)?\s*(보유|필수|필요|기업)|법인\s*(설립|사업자)\s*(필수|필요|보유)|중소기업\s*확인서' and not restriction @> array['사업자등록·법인 필요'::text] then
    restriction:=restriction||'사업자등록·법인 필요'::text; end if;
  if t ~* '\yPre-?\s*A\y|\ySeries\s*[A-C]\y|시리즈\s*[A-C]|프리\s*에이' and not restriction @> array['투자 단계 한정'::text] then
    restriction:=restriction||'투자 단계 한정'::text; end if;
  if t ~* '(?:업력|설립|창업)\s*\d+\s*년\s*이상' and not restriction @> array['업력 하한 조건'::text] then
    restriction:=restriction||'업력 하한 조건'::text; end if;
  if t ~* '수출\s*실적|수출\s*\d+\s*(만|억)' and not restriction @> array['수출 실적 요건'::text] then
    restriction:=restriction||'수출 실적 요건'::text; end if;
  if t ~* '(본사|기업)\s*이전|이전\s*조건|관내\s*이전' and not restriction @> array['소재지 이전 필요'::text] then
    restriction:=restriction||'소재지 이전 필요'::text; end if;
 region:=(select (regexp_match(coalesce(p_title,''),'^\s*[\[【]\s*([가-힣]{2,8}(?:\s*[·ㆍ]\s*[가-힣]{2,8})?)\s*[\]】]'))[1]);
 if region is not null then
  restriction:=restriction||(region||' 지역 사업')::text;
 else
  region:=(select (regexp_match(t,'([가-힣]{2,6}(?:특별자치[시도]|특별시|광역시|[가-힣]도|[가-힣]시|[가-힣]군|[가-힣]구))\s*(?:에|내|의)?\s*소재'))[1]);
  if region is not null then
   restriction:=restriction||(region||' 소재 기업')::text;
  elsif t ~* '관내\s*(?:에\s*)?소재|관내\s*(?:기업|업체|법인)' then
   restriction:=restriction||'주관기관 관내 소재 기업'::text;
  end if;
 end if;
 if cardinality(restriction)=0 then
  return jsonb_build_object('relevance_status','GFC_RELEVANT','startup_leverage','HIGH',
   'applicability','BROAD','startup_leverage_reason',core_reason,'restriction_summary',null); end if;
 restriction_summary:=left(array_to_string(restriction,' · '),200);
 return jsonb_build_object('relevance_status','CONDITIONAL','startup_leverage','HIGH',
  'applicability','RESTRICTED','startup_leverage_reason',core_reason,
  'restriction_summary',restriction_summary);
end $fn$;
revoke all on function startup_radar.gfc_relevance_v1_1(text,text,text) from public,anon,authenticated;
grant execute on function startup_radar.gfc_relevance_v1_1(text,text,text) to service_role;
