-- GENERATED by tools/export_stage_sql.py from radar/stage.py (gfc-stage-v1.0).
-- Do not edit by hand; regenerate when the rule tables change.
do $$ begin
 if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace
                where n.nspname='startup_radar' and t.typname='stage_hit') then
  create type startup_radar.stage_hit as (code text, hits bigint, ord integer);
 end if;
end $$;

create or replace function startup_radar.stage_label(p_code text) returns text
language sql immutable security invoker set search_path='' as $$
 select label from (values ('STAGE_0','아이디어 전'),('STAGE_1','팀 구성·아이디어'),('STAGE_2','랜딩·시장검증'),('STAGE_3','MVP·PoC'),('STAGE_4','사업자·법인 이후')) as s(code,label) where s.code=p_code
$$;

create or replace function startup_radar.gfc_stage_v1_0(
 p_title text,p_applicant text,p_support text)
returns text[] language plpgsql immutable security invoker set search_path='' as $fn$
declare
 t_all text; t_desc text; n bigint; found startup_radar.stage_hit[]:='{}';
begin
 -- STAGE_4 never reads the applicant summary: eligibility is not stage evidence.
 t_desc:=concat_ws(E'\n',left(coalesce(p_title,''),200),left(coalesce(p_support,''),400));
 t_all:=concat_ws(E'\n',left(coalesce(p_title,''),200),left(coalesce(p_applicant,''),500),left(coalesce(p_support,''),400));
  n:=(select count(*) from regexp_matches(t_all,'창업\s*입문|창업\s*기초|문제\s*(발굴|정의|탐색)|아이디어\s*발굴|창업\s*(마인드|이해)|기업가\s*정신\s*(교육|캠프|부트캠프)|창업\s*(캠프|부트캠프)|창업\s*교육\s*(과정|프로그램)|창업\s*첫\s*걸음|예비\s*창업\s*교육','gi'));
  if n>0 then found:=found||row('STAGE_0',n,0)::startup_radar.stage_hit; end if;
  n:=(select count(*) from regexp_matches(t_all,'팀\s*빌딩|팀\s*구성|아이디어톤|해커톤|아이디어\s*(고도화|경진|공모|구체화|검증)|창업\s*아이디어|창업팀\s*(모집|선발|구성)','gi')) + (select count(*) from regexp_matches(t_all,'예비\s*창업(자|팀|패키지)|창업\s*준비|창업\s*동아리|창업\s*(경진대회|공모전|대회|챌린지)','gi'));
  if n>0 then found:=found||row('STAGE_1',n,1)::startup_radar.stage_hit; end if;
  n:=(select count(*) from regexp_matches(t_all,'고객\s*(발굴|검증|인터뷰|확보)|시장\s*검증|수요\s*(검증|조사|테스트)|\yBM\y\s*검증|비즈니스\s*모델\s*(검증|개발|수립)|랜딩\s*페이지|초기\s*(고객|사용자)|사용자\s*테스트|PMF|린\s*스타트업|문제\s*해결\s*검증','gi'));
  if n>0 then found:=found||row('STAGE_2',n,2)::startup_radar.stage_hit; end if;
  n:=(select count(*) from regexp_matches(t_all,'\yMVP\y|프로토타입|시제품|시작품|제품\s*(개발|제작|고도화)|\yPoC\y|실증|파일럿|테스트\s*베드|리빙\s*랩|기술\s*검증|기술\s*(개발|고도화)\s*지원','gi')) + (select count(*) from regexp_matches(t_all,'초기\s*사업화|사업화\s*(지원|연계)|창업\s*보육|보육\s*센터|입주\s*(기업|팀|공간|모집|신청)|창업\s*공간|사업장\s*주소지|법인\s*설립[^\n]{0,12}(지원|대행|제공|컨설팅|안내)|사업자\s*등록[^\n]{0,10}(지원|대행)|초기\s*창업(자|기업|패키지)|액셀러레이[팅터]|배치\s*(프로그램|모집|선발)|accelerat|인큐베이[팅션]|레지던시|residency|초기\s*IR|\yIR\s*(교육|코칭|피칭\s*스킬)','gi'));
  if n>0 then found:=found||row('STAGE_3',n,3)::startup_radar.stage_hit; end if;
  n:=(select count(*) from regexp_matches(t_desc,'오픈\s*이노베이션|open\s*innovation|대\-?중견\s*(기업\s*)?(연계|협업|매칭)|기업\s*협업\s*프로젝트|수요\s*기업\s*매칭|공동\s*사업화','gi')) + (select count(*) from regexp_matches(t_desc,'투자\s*(유치|매칭|연계|설명회|상담회)|\yVC\y|벤처\s*캐피탈|데모\s*데이|demo\s*day|investor\s*day|투자자\s*(매칭|미팅)|시리즈\s*[A-C]|\yPre-?\s*A\y|팁스|\yTIPS\y|후속\s*투자','gi')) + (select count(*) from regexp_matches(t_desc,'사업화\s*자금|스케일\s*업|scale-?up|성장\s*(지원|단계|자금)|도약\s*(패키지|지원)|매출\s*(확대|성장)|양산','gi')) + (select count(*) from regexp_matches(t_desc,'해외\s*(진출|실증|파트너|법인|현지화|판로)|글로벌\s*(진출|실증|파트너|액셀러|스케일)|수출\s*(지원|기업|바우처|계약)|바이어\s*(매칭|상담|발굴)|현지\s*(진출|파트너|투자자)|국제\s*(전시|박람회)\s*(참가|참여)|통합관|파빌리온','gi'));
  if n>0 then found:=found||row('STAGE_4',n,4)::startup_radar.stage_hit; end if;
 if cardinality(found)=0 then return '{}'::text[]; end if;
 return coalesce((select array_agg(code order by ord) from (
   select h.code,h.ord from unnest(found) as h order by h.hits desc, h.ord asc limit 2) top),'{}'::text[]);
end $fn$;
revoke all on function startup_radar.gfc_stage_v1_0(text,text,text) from public,anon,authenticated;
grant execute on function startup_radar.gfc_stage_v1_0(text,text,text) to service_role;
grant execute on function startup_radar.stage_label(text) to authenticated,service_role;
